{"": ["DATA RACE in tun.(*Device).Write", "kvm: panic: Watchdog goroutine is stuck (6)", "panic: wd changed: \"/tmp\" -> \"(unreachable)/\" (2)", "gvisor test error: SYZFATAL: BUG: simple call failed: {Flags:NUM Signal:[] Cover:[] Comps: Errno:NUM} (2)", "panic: Sentry detected stuck tasks (17)", "panic: unbalance unlock: transport.endpointMutex:LINE:", "lost connection to test machine (8)", "panic: WARNING: circular locking detected: tmpfs.filesystemRWMutex -> kernel.taskSetRWMutex:", "panic: WARNING: circular locking detected: vfs.inotifyEventMutex -> mm.mappingRWMutex:", "panic: WARNING: circular locking detected: tmpfs.filesystemRWMutex -> vfs.inotifyEventMutex:", "panic: WARNING: circular locking detected: vfs.inotifyEventMutex -> mm.activeRWMutex:", "panic: WARNING: circular locking detected: mm.mappingRWMutex -> tmpfs.filesystemRWMutex:", "panic: WARNING: circular locking detected: tmpfs.inodeMutex -> mm.mappingRWMutex:", "SYZFATAL: executor NUM failed NUM times: executor NUM: exit status NUM", "gvisor test error: timed out (4)", "DATA RACE in fuse.(*DeviceFD).filesystemIsInitialized", "SYZFAIL: tun: can't open /dev/net/tun (2)", "FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF (4)", "panic: runtime error: slice bounds out of range [12:LINE]", "panic: Unknown error: header is malformed", "no output from test machine (10)", "panic: Watchdog goroutine is stuck (3)", "Invalid request partialResult in aio", "fatal error: entry failed (2)", "panic: Unknown syscall 165 error: strconv.ParseInt: parsing \"\": invalid syntax", "fatal error: unknown caller pc (3)", "DATA RACE in fs.Rename (4)", "Invalid request partialResult in splice (3)", "panic: invalid range: [ADDR, ADDR)", "panic: Task goroutine switching from state 2 (expected 1) to 3", "panic: Task goroutine switching from state 3 (expected 1) to 2", "fatal error: too many address space collisions for -race mode (2)", "fatal error: out of memory (4)", "FATAL ERROR: loading sandbox: file does not exist", "fatal error: fault (2)", "SIGSEGV: segmentation violation"], "fixed": ["panic: runtime error: invalid memory address or nil pointer dereference (11)", "panic: runtime error: slice bounds out of range [:NUM] with capacity NUM", "panic: close of closed channel", "DATA RACE in vfs.(*VirtualFilesystem).setPropagation", "DATA RACE in bufferv2.newChunk", "DATA RACE in vfs.(*VirtualFilesystem).GenerateProcMountInfo", "panic: runtime error: integer divide by zero (2)", "panic: nested locking: kernel.taskSetRWMutex:", "gvisor test error: panic: WARNING: circular locking detected: mm.activeRWMutex -> kernel.taskSetRWMutex:", "panic: Decrementing non-positive ref count ADDR, owned by kernel.ProcessGroup (2)", "kvm: panic: Sentry detected stuck tasks (9)", "gvisor build error (15)", "panic: cgroupfs: pids controller pending pool would be negative if charge was allowed: current pool: NUM, proposed charg", "panic: addresses IP and fe80::aa do not have the same length", "DATA RACE in fuse.newFUSEFilesystem", "panic: WARNING: circular locking detected: cgroupfs.pidsControllerMutex -> mm.mappingRWMutex:", "panic: WARNING: circular locking detected: tmpfs.inodeMutex -> mm.activeRWMutex:", "panic: Sentry detected stuck tasks (16)", "kvm: panic: Sentry detected stuck tasks (7)", "panic: invalid allocation length: 0x0 (4)", "panic: WARNING: circular locking detected: kernel.taskSetRWMutex -> mm.activeRWMutex:", "panic: runtime error: index out of range [-NUM]", "DATA RACE in fuse.(*connection).callFutureLocked", "DATA RACE in fuse.(*DeviceFD).Read", "DATA RACE in fuse.newFUSEConnection", "DATA RACE in fuse.(*DeviceFD).PWrite", "DATA RACE in fuse.(*DeviceFD).PRead", "DATA RACE in fuse.(*DeviceFD).Seek", "panic: unexpected tcp state in processor: BOUND", "DATA RACE in cgroupfs.(*memsData).Write", "panic: unknown network protocol number NUM", "panic: runtime error: invalid memory address or nil pointer dereference (10)", "DATA RACE in kernfs.(*OrderedChildren).checkExistingLocked", "panic: Inode doesn't match what kernfs thinks! OrderedChild: &{dir:{InodeNoopRefCount:{InodeTemporary:{}} InodeAlwaysVal", "DATA RACE in bitmap.(*Bitmap).Maximum", "kvm: lost connection to test machine", "lost connection to test machine (6)", "DATA RACE in transport.(*connectionedEndpoint).Connect.func1 (2)", "kvm: panic: Sentry detected stuck tasks (6)", "panic: Sentry detected stuck tasks (15)", "Invalid request partialResult in sendto (3)", "kvm: panic: Sentry detected stuck tasks (5)", "panic: runtime error: invalid memory address or nil pointer dereference (9)", "DATA RACE in fuse.(*connection).callFuture (2)", "panic: Unknown syscall NUM error: payload too small. Minimum data lenth required: NUM, but got data length NUM", "fatal error: sync: unlock of unlocked mutex", "DATA RACE in fuse.(*connection).callFuture", "DATA RACE in fuse.(*connection).initProcessReply", "DATA RACE in fuse.(*DeviceFD).writeLocked", "DATA RACE in fuse.(*connection).Call", "DATA RACE in fuse.(*DeviceFD).Release", "DATA RACE in stack.(*PacketBuffer).reset (2)", "panic: runtime error: invalid memory address or nil pointer dereference (8)", "panic: Incrementing non-positive count ADDR on stack.PacketBuffer", "DATA RACE in mqfs.FilesystemType.GetFilesystem", "gvisor build error (13)", "panic: runtime error: index out of range [NUM] with length NUM (2)", "panic: PullUp failed (2)", "DATA RACE in transport.(*connectionedEndpoint).Listen", "DATA RACE in udp.(*endpoint).Connect (2)", "kvm: panic: Sentry detected stuck tasks (4)", "panic: Sentry detected stuck tasks (14)", "DATA RACE in stack.(*PacketBuffer).reset", "panic: runtime error: makeslice: len out of range (4)", "SYZFAIL: tun: can't open /dev/net/tun", "kvm: no output from test machine (2)", "DATA RACE in cgroupfs.(*cpusData).Generate", "DATA RACE in cgroupfs.(*cpusData).Write", "panic: runtime error: index out of range [NUM] with length NUM", "panic: interface conversion: kernfs.Inode is nil, not *mqfs.rootInode", "panic: runtime error: invalid memory address or nil pointer dereference (7)", "panic: kernfs.Dentry.DecRef() called without holding a reference", "panic: Only permission mask must be set: ADDR", "gvisor build error (11)", "FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF (3)", "DATA RACE in safemem.Copy (3)", "panic: runtime error: slice bounds out of range [:LINE] with capacity 0", "panic: Sentry detected stuck tasks (13)", "Invalid request partialResult in pwritev", "kvm: panic: Watchdog goroutine is stuck (4)", "panic: runtime error: slice bounds out of range [40:LINE]", "Invalid request partialResult in sendto (2)", "kvm: panic: Sentry detected stuck tasks (2)", "panic: Sentry detected stuck tasks (12)", "DATA RACE in msgqueue.(*Queue).pop", "panic: Sentry detected stuck tasks (11)", "panic: runtime error: makeslice: len out of range (3)", "panic: unknown error: SIGBUS at ADDR", "DATA RACE in safemem.Copy (2)", "panic: runtime error: slice bounds out of range [2:LINE]", "DATA RACE in buffer.(*buffer).Remove", "kvm: no output from test machine", "no output from test machine (9)", "panic: unable to find an index for ID: 0", "DATA RACE in atomic.CompareAndSwapInt32 (4)", "panic: FIN segments must be the final segment in the write list.", "FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF (2)", "panic: Incrementing non-positive count ADDR on kernel.ProcessGroup (2)", "kvm: panic: Watchdog goroutine is stuck (3)", "panic: Watchdog goroutine is stuck (2)", "panic: Incrementing non-positive count ADDR on vfs.Filesystem (2)", "panic: PullUp failed", "panic: Incrementing non-positive count ADDR on vfs.Filesystem", "DATA RACE in cgroupfs.FilesystemType.GetFilesystem", "panic: Sentry detected stuck tasks (10)", "kvm: panic: Watchdog goroutine is stuck (2)", "panic: Watchdog goroutine is stuck", "panic: makechan: size out of range", "fatal error: unexpected signal during runtime execution", "kvm: panic: Watchdog goroutine is stuck", "Invalid request partialResult in write (2)", "kvm: panic: Sentry detected stuck tasks", "panic: Sentry detected stuck tasks (9)", "panic: Sentry detected stuck tasks (8)", "no output from test machine (8)", "panic: running on goroutine 582 (task goroutine for kernel.Task ADDR is 400)", "panic: unknown error *tcpip.ErrMalformedHeader", "panic: Sentry detected stuck tasks (7)", "panic: wd changed: \"/tmp\" -> \"(unreachable)/\"", "Invalid request partialResult in sendto", "FATAL ERROR: executing processes for container: executing command \"/syz-fuzzer -executor=/syz-executor -name=vm-1 -arch=", "panic: Incrementing non-positive count ADDR on kernel.ProcessGroup", "panic: Child \".\" for parent Dentry &{vfsd:{mu:{m:{Mutex:{state:LINE sema:LINE}}} dead:false mounts:LINE impl:ADDR} refs:", "panic: Start ADDR + offset ADDR overflows?", "panic: Decrementing non-positive ref count ADDR, owned by vfs.FileDescription", "DATA RACE in safemem.Copy", "panic: Sentry detected stuck tasks (6)", "panic: IPv6 payload too large: NUM, must be <= NUM", "panic: buffer too long by 8 bytes", "panic: runtime error: invalid memory address or nil pointer dereference (5)", "panic: invalid pipe flags: must be readable, writable, or both", "DATA RACE in stack.(*NIC).DeliverNetworkPacket", "panic: runtime error: integer divide by zero", "panic: error when reading RouterAlert option's data bytes: EOF", "DATA RACE in raw.(*endpoint).HandlePacket", "panic: header.ScopeForIPv6Address(172.20.20.170): bad address", "panic: close of nil channel (2)", "panic: Unknown syscall 165 error: strconv.ParseInt: parsing \"ADDR\": invalid syntax", "DATA RACE in header.ICMPv6Checksum", "panic: Unknown syscall 8 error: EOF", "panic: Stack for running G's are skipped while panicking.", "panic: Sentry detected stuck tasks (5)", "DATA RACE in log.GoogleEmitter.Emit", "panic: runtime error: slice bounds out of range [255:LINE]", "panic: cacheLocked called on a dentry which has already been destroyed: &{{{{0 0}} true 0 ADDR} -1 ADDR 1 ADDR NUM false", "gvisor boot error: FATAL ERROR: running container: creating container: open /sys/fs/cgroup/devices/ci-gvisor-kvm-proxy-overlay-sandbox-test", "panic: Sentry detected stuck tasks (4)", "panic: Incrementing non-positive count ADDR on tmpfs.inode", "panic: Sentry detected stuck tasks (3)", "panic: runtime error: invalid memory address or nil pointer dereference (4)", "panic: Decrementing non-positive ref count ADDR, owned by *mm.SpecialMappable", "panic: Sentry detected stuck tasks (2)", "no output from test machine (7)", "panic: runtime error: makeslice: len out of range (2)", "panic: Incrementing non-positive ref count ADDR owned by *mm.SpecialMappable", "panic: Child \"\" for parent Dentry &{vfsd:{mu:{Mutex:{state:LINE sema:LINE}} dead:false mounts:LINE impl:ADDR} DentryRefs", "panic: unknown error: EOF", "no output from test machine (6)", "no output from test machine (5)", "panic: Sentry detected stuck tasks", "DATA RACE in tcp.(*endpoint).bindLocked", "panic: runtime error: invalid memory address or nil pointer dereference (3)", "DATA RACE in transport.(*connectionedEndpoint).Connect.func1", "panic: Sentry detected 1 stuck task(s):", "DATA RACE in atomic.LoadInt64", "DATA RACE in fs.(*File).offsetForAppend", "DATA RACE in kernel.(*Task).accountTaskGoroutineEnter", "panic: D0415 01:LINE.ADDR 8857 transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 95}", "panic: close of nil channel", "panic: D0414 08:LINE.ADDR NUM transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "panic: D0414 11:LINE.ADDR NUM transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 95}", "panic: D0414 14:LINE.ADDR NUM task_exit.go:LINE] [ 98] Transitioning from exit state TaskExitNone to TaskExitInitiate", "panic: D0414 16:LINE.ADDR 5236 transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "panic: D0414 13:LINE.ADDR NUM transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "panic: interface conversion: context.Context is kernel.taskAsyncContext, not *kernel.Task", "panic: runtime error: makeslice: len out of range", "DATA RACE in tcp.(*endpoint).Readiness", "DATA RACE in netstack.(*SocketOperations).SetSockOpt", "DATA RACE in tcp.(*endpoint).SetSockOpt", "DATA RACE in udp.(*endpoint).SetSockOptBool", "no output from test machine (3)", "panic: Watchdog goroutine is stuck:", "panic: Sentry detected 4 stuck task(s):", "fatal error: out of memory (3)", "fatal error: too many address space collisions for -race mode", "fatal error: concurrent map iteration and map write (2)", "DATA RACE in fsutil.(*InodeSimpleExtendedAttributes).ListXattr", "lost connection to test machine (4)", "DATA RACE in udp.(*endpoint).Connect", "DATA RACE in fsutil.(*InodeSimpleExtendedAttributes).RemoveXattr", "DATA RACE in tcp.(*endpoint).windowCrossedACKThreshold", "DATA RACE in stack.(*TransportEndpointInfo).AddrNetProto", "fatal error: concurrent map read and map write (2)", "panic: runtime error: index out of range [1] with length 0", "DATA RACE in netstack.(*SocketOperations).fetchReadView", "DATA RACE in fsutil.(*InodeSimpleExtendedAttributes).GetXattr", "DATA RACE in fs.(*UnstableAttr).SetOwner (2)", "DATA RACE in fs.mayDelete", "DATA RACE in fs.(*Dirent).IncRef", "panic: Incrementing non-positive ref count (4)", "panic: munmap(ADDR, NUM)) failed: function not implemented (3)", "panic: munmap(0, ADDR)) failed: function not implemented (3)", "panic: wait failed: the process NUM:NUM exited: 1f (err <nil>) (2)", "panic: wait failed: the process 9793:LINE exited: 1f (err <nil>)", "panic: wait failed: the process 4877:LINE exited: 1f (err <nil>)", "panic: runtime error: slice bounds out of range [:LINE] with capacity 16", "panic: wait failed: the process NUM:LINE exited: 1f (err <nil>) (4)", "DATA RACE in refs.(*WeakRef).init (2)", "DATA RACE in refs.(*AtomicRefCount).DecRefWithDestructor", "panic: interface conversion: refs.RefCounter is *fs.File, not *fs.Dirent", "Invalid request partialResult in splice (2)", "fatal error: out of memory (2)", "panic: invalid allocation length: 0x0 (3)", "DATA RACE in fs.Rename (3)", "DATA RACE in tty.(*queue).readableSize", "panic: Incrementing non-positive ref count (3)", "panic: munmap(ADDR, 1000)) failed: function not implemented (3)", "DATA RACE in fs.(*UnstableAttr).SetOwner", "DATA RACE in fsutil.(*InodeSimpleAttributes).SetPermissions", "no output from test machine (2)", "DATA RACE in fs.Rename (2)", "Invalid request partialResult in sendfile (2)", "Invalid request partialResult in splice", "lost connection to test machine (3)", "panic: node.Readdir returned offset -ADDR less than input offset ADDR", "DATA RACE in ramfs.(*dirFileOperations).Readdir", "no output from test machine", "DATA RACE in kernel.(*Kernel).EmitUnimplementedEvent", "DATA RACE in atomic.AddInt32", "panic: Unknown syscall 85 error: link should be resolved via Readlink()", "panic: Unknown syscall 2 error: link should be resolved via Readlink()", "panic: Unknown syscall 257 error: link should be resolved via Readlink()", "panic: Incrementing non-positive ref count (2)", "DATA RACE in atomic.AddInt64", "DATA RACE in fs.(*lockedReader).Read", "DATA RACE in atomic.StoreInt64", "DATA RACE in mm.(*MemoryManager).Brk", "panic: hashed child \"stat\\t\\xe9\\xdc\\xdf\\x02\\x02\\x98\\xcc\\xf3<\\xdf-\\xea\\xc8\\xc1w\\xff\\x17\\x12H\\xe9\\x11\\x93Q\\nI\\xf81U\\ro}\\xe", "DATA RACE in fs.(*Dirent).fullName", "panic: hashed over a positive child \"file0\"", "DATA RACE in tty.(*lineDiscipline).masterReadiness", "DATA RACE in tty.(*queue).WriteFromBlocks", "panic: runtime error: index out of range (2)", "DATA RACE in atomic.CompareAndSwapInt32 (2)", "DATA RACE in atomic.CompareAndSwapInt32", "DATA RACE in netlink.(*Socket).SetSockOpt", "DATA RACE in dev.(*randomDevice).GetFile", "DATA RACE in fsutil.(*InodeSimpleAttributes).UnstableAttr", "panic: invalid allocation length: 0x0 (2)", "gvisor boot error (3)", "DATA RACE in shm.(*Registry).findByKey", "gvisor test error (2)", "panic: invalid type: int", "panic: ptrace set regs failed: input/output error", "Invalid request partialResult in sendfile", "panic: Decrementing non-positive ref count", "panic: ptrace status unexpected: got 9, wanted stopped (2)", "panic: invalid allocation length: 0x0", "DATA RACE in fs.(*Dirent).getDotAttrs", "panic: runtime error: invalid memory address or nil pointer dereference (2)", "gvisor boot error", "DATA RACE in kernel.(*Task).setKUIDsUncheckedLocked", "DATA RACE in fs.(*Dirent).hashChildParentSet", "DATA RACE in waiter.(*Entry).Prev", "DATA RACE in waiter.(*Entry).Next", "fatal error: concurrent map read and map write", "DATA RACE in waiter.(*Entry).SetNext", "fatal error: concurrent map writes", "panic: runtime error: index out of range", "DATA RACE in waiter.(*Entry).SetPrev", "DATA RACE in waiter.(*Queue).Notify", "DATA RACE in unix.(*connectionlessEndpoint).UnidirectionalConnect", "panic: runtime error: invalid memory address or nil pointer dereference", "DATA RACE in kernel.(*Task).exitNotifyLocked", "panic: invalid segment range [ADDR, ADDR)", "DATA RACE in kernel.(*Task).Clone", "DATA RACE in fs.(*Watch).Notify", "lost connection to test machine (2)", "DATA RACE in fs.Rename", "panic: MountNamespace.FindInode: path is empty", "panic: runtime error: slice bounds out of range", "DATA RACE in proc.forEachMountSource", "DATA RACE in kernel.(*Task).Value", "DATA RACE in semaphore.(*Set).checkPerms", "DATA RACE in semaphore.(*Registry).RemoveID", "DATA RACE in queue.(*Queue).Enqueue", "DATA RACE in unix.(*queueReceiver).RecvQueuedSize", "panic: munmap(ADDR, c6000)) failed: function not implemented", "DATA RACE in unix.(*streamQueueReceiver).RecvQueuedSize", "DATA RACE in kernel.(*FSContext).SetWorkingDirectory", "DATA RACE in proc.(*mountInfoFile).ReadSeqFileData.func1", "DATA RACE in kernel.(*FSContext).SetRootDirectory", "panic: munmap(ADDR, 0)) failed: invalid argument"], "invalid": ["DATA RACE in kernel.(*Task).MemoryManager", "panic: cgroupfs: pids controller attempted to remove pending charge for Task ADDR, but task didn't have pending charges,", "kvm: no output from test machine (3)", "panic: WARNING: circular locking detected: kernel.taskSetRWMutex -> mm.mappingRWMutex:", "panic: unlock of an unknow lock", "panic: WARNING: circular locking detected: tmpfs.filesystemRWMutex -> mm.activeRWMutex:", "suppressed report", "kvm: panic: Sentry detected stuck tasks (8)", "panic: nested locking: kernfs.filesystemRWMutex:", "gvisor test error: SYZFATAL: BUG: host setup failed: failed to run [\"/syz-executor\" \"setup\"]: exit status NUM", "SYZFAIL: input command overflows input", "SYZFAIL: open of /sys/kernel/debug/kcov failed", "kvm: lost connection to test machine (2)", "kvm: panic: Watchdog goroutine is stuck (5)", "gvisor test error: SYZFATAL: BUG: simple call failed: {Flags:NUM Signal:[] Cover:[] Comps: Errno:NUM}", "SYZFAIL: tun: ioctl(TUNSETIFF) failed", "lost connection to test machine (7)", "SYZFAIL: result overflows kMaxCommands (2)", "gvisor boot error: panic: nested locking: kernel.taskSetRWMutex:", "panic: Decrementing non-positive ref count ADDR, owned by kernel.ProcessGroup", "gvisor test error: lost connection to test machine (7)", "SYZFATAL: executor NUM failed NUM times: bad call NUM index ADDR/NUM", "gvisor test error: timed out (3)", "DATA RACE in fuse.(*DeviceFD).Release (2)", "panic: running on goroutine ADDR (task goroutine for kernel.Task ADDR is ADDR)", "SYZFAIL: both fault injection and rerun are enabled for the same call", "panic: disabled syscall (2)", "gvisor boot error: init process did not start (4)", "SYZFAIL: bad argument type", "gvisor build error (14)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (13)", "gvisor test error: lost connection to test machine (6)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (12)", "panic: interface conversion: stack.TransportEndpoint is nil, not *tcp.endpoint", "SYZFAIL: out of opened kcov threads", "gvisor build error (12)", "fatal error: unexpected signal during runtime execution (2)", "SYZFAIL: bad thread state in completion", "gvisor test error: timed out (2)", "kvm: panic: Sentry detected stuck tasks (3)", "fatal error: D0415 08:LINE.ADDR 1 task_signals.go:LINE] [ 7151] Signal 23: delivering to handler", "gvisor test error: lost connection to test machine (5)", "lost connection to test machine (5)", "gvisor boot error: init process did not start (3)", "FATAL ERROR: running container: sandbox is still running", "gvisor boot error: panic: unable to activate mm: creating stub process: resource temporarily unavailable", "panic: ptrace status unexpected: got 9, wanted stopped (4)", "FATAL ERROR: executing processes for container: executing command \"/syz-fuzzer -executor=/syz-executor -name=vm-0 -arch=", "gvisor boot error: panic: error initializing first thread: resource temporarily unavailable", "gvisor test error: panic: error initializing first thread: resource temporarily unavailable (4)", "gvisor build error (10)", "gvisor boot error: FATAL ERROR: Error reading mounts file: error unmarshaling mounts: unexpected end of JSON input (2)", "panic: trying to use inactive address space? (4)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (11)", "syzkaller: make host failed: failed to run [\"make\" \"host\" \"ci\"]: exit status 2 (4)", "SYZFAIL: result overflows kMaxCommands", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 2 (5)", "panic: unable to activate mm: creating stub process: cannot allocate memory (2)", "panic: Decrementing non-positive ref count ADDR, owned by vfs.FileDescription (2)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 2 (4)", "gvisor boot error: FATAL ERROR: running container: starting container: starting root container: starting sandbox: failed to setupFS: creati", "gvisor boot error: FATAL ERROR: running container: starting container: starting root container: urpc method \"containerManager.StartRoot\" fa", "gvisor build error (9)", "gvisor test error: fatal error: newosproc (4)", "gvisor boot error: fatal error: newosproc (3)", "gvisor boot error: fatal error: unexpected signal during runtime execution", "panic: Decrementing non-positive ref count (2)", "gvisor test error: no output from test machine (2)", "panic: disabled syscall", "panic: trying to use inactive address space? (3)", "gvisor build error (8)", "fatal error: runtime: netpollBreak write failed", "DATA RACE in fs.(*Dirent).IsRoot", "gvisor boot error: DATA RACE in tcp.(*processor).start", "syzkaller: make host failed: failed to run [\"make\" \"host\" \"ci\"]: exit status 2 (3)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (10)", "gvisor build error (7)", "gvisor boot error: init process did not start (2)", "gvisor test error: panic: error initializing first thread: resource temporarily unavailable (3)", "gvisor test error: timed out", "gvisor boot error: fatal error: newosproc (2)", "gvisor test error: fatal error: newosproc (3)", "gvisor test error: no output from test machine", "gvisor test error: lost connection to test machine (4)", "panic: runtime error: index out of range [1] with length 1 (2)", "panic: Watchdog goroutine is stuck: (2)", "fatal error: index out of range", "panic: Sentry detected 13 stuck task(s):", "gvisor test error: fatal error: newosproc (2)", "FATAL ERROR: loading container NAME: file does not exist", "FATAL ERROR: loading container NAME: open /syzkaller/managers/kvm-proxy-overlay-sandbox/workdir/gvisor_root/ci-gvisor-kv", "panic: CopyIn raised signal 7 at ADDR, which is outside source [ADDR, ADDR)", "DATA RACE in stack.(*Route).WritePacket", "panic: Sentry detected 7 stuck task(s):", "FATAL ERROR: loading container NAME: open /syzkaller/managers/ptrace-direct-overlay-host/workdir/gvisor_root/ci-gvisor-p", "fatal error: invalid g status", "no output from test machine (4)", "FATAL ERROR: loading container NAME: open /syzkaller/managers/ptrace-proxy-sandbox-race/workdir/gvisor_root/ci-gvisor-pt", "fatal error: unknown caller pc (2)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 2 (3)", "panic: executing disabled syscall fsconfig$FSCONFIG_SET_FD", "FATAL ERROR: loading container NAME: open /syzkaller/managers/ptrace-direct-overlay-host-race/workdir/gvisor_root/ci-gvi", "gvisor test error: panic: error initializing first thread: resource temporarily unavailable (2)", "syzkaller: make target failed: failed to run [\"make\" \"target\"]: exit status 2 (4)", "panic: trying to use inactive address space? (2)", "gvisor test error: lost connection to test machine (3)", "gvisor boot error: FATAL ERROR: running container: starting container: starting root container: starting sandbox: creating filesystem for c", "panic: munmap(ADDR, ADDR)) failed: function not implemented (2)", "gvisor build error (6)", "gvisor test error: panic: unable to activate mm: creating stub process: resource temporarily unavailable", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 2 (2)", "fatal error: D0313 06:LINE.ADDR NUM task_block.go:LINE] [ 7039] Interrupt queued", "fatal error: faultD0313 09:LINE.ADDR NUM task_log.go:LINE] [ NUM] ADDR: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0", "fatal error: faultD0313 09:LINE.ADDR NUM task_log.go:LINE] [ NUM] ADDR: 9f 97 79 f0 0c e6 c3 bf 3c 41 65 a1 c7 b1 c9 e", "fatal error: D0313 08:LINE.ADDR NUM task_signals.go:LINE] [ 8373] Discarding ignored signal 18", "gvisor test error: lost connection to test machine (2)", "fatal error: D0312 17:LINE.ADDR NUM task_block.go:LINE] [ 40] Interrupt queued", "fatal error: faultD0312 04:LINE.ADDR NUM task_block.go:LINE] [ 1] Interrupt queued", "fatal error: faultD0309 15:LINE.ADDR NUM task_exit.go:LINE] [ NUM] Transitioning from exit state TaskExitZombie to Tas", "fatal error: D0310 15:LINE.ADDR NUM task_signals.go:LINE] [ NUM] Notified of signal 7", "fatal error: D0310 13:LINE.ADDR NUM transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "fatal error: faultD0308 22:LINE.ADDR NUM task_log.go:LINE] [ NUM] R8 = ADDR", "fatal error: faultD0306 01:LINE.ADDR NUM task_exit.go:LINE] [ NUM] Transitioning from exit state TaskExitNone to TaskE", "fatal error: D0308 03:LINE.ADDR NUM task_block.go:LINE] [ 1] Interrupt queued", "fatal error: D0309 08:LINE.ADDR 2009 task_signals.go:LINE] [ 86] Discarding ignored signal 17", "fatal error: D0308 19:LINE.ADDR NUM task_signals.go:LINE] [ 8] Notified of signal 7", "fatal error: I0306 06:LINE.ADDR NUM loader.go:LINE] Received external signal 23, mode: Process", "fatal error: faultD0309 03:LINE.ADDR NUM task_block.go:LINE] [ 4625] Interrupt queued", "fatal error: faultD0309 10:LINE.ADDR NUM task_signals.go:LINE] [ NUM] Signal 7: delivering to handler", "fatal error: D0307 12:LINE.ADDR NUM task_log.go:LINE] [ 177] ADDR: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00", "fatal error: D0311 06:LINE.ADDR NUM task_exit.go:LINE] [ NUM] Transitioning from exit state TaskExitZombie to TaskExit", "fatal error: D0310 15:LINE.ADDR NUM task_run.go:LINE] [ 31] Restarting syscall 202 after errno 512: not interrupted b", "fatal error: faultD0306 17:LINE.ADDR NUM transport_flipcall.go:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "fatal error: faultD0310 12:LINE.ADDR NUM transport_flipcall.go:LINE] send [channel @ADDR] Tgetxattr{FID: 1, Name: trus", "fatal error: faultD0309 09:LINE.ADDR NUM transport_flipcall.go:LINE] send [channel @ADDR] Tgetxattr{FID: 1, Name: trus", "fatal error: faultD0306 00:LINE.ADDR NUM task_block.go:LINE] [ 133] Interrupt queued", "fatal error: D0308 23:LINE.ADDR NUM task_signals.go:LINE] [ NUM] Signal 9: terminating thread group", "fatal error: faultD0307 08:LINE.ADDR NUM task_block.go:LINE] [ NUM] Interrupt queued", "fatal error: D0305 20:LINE.ADDR 4774 task_block.go:LINE] [ 2] Interrupt queued", "fatal error: D0305 11:LINE.ADDR NUM task_log.go:LINE] [ 945] ADDR: 75 89 4a 00 00 00 00 00 06 00 00 00 00 00 00 00", "fatal error: D0305 13:LINE.ADDR NUM task_block.go:LINE] [ NUM] Interrupt queued", "fatal error: D0304 21:LINE.ADDR NUM task_log.go:LINE] [ NUM] ADDR: 79 7a 31 00 79 7a 31 00 75 70 2e 70 72 6f 63 73", "fatal error: I0304 17:LINE.ADDR NUM loader.go:LINE] Received external signal 23, mode: Process", "fatal error: faultD0304 15:LINE.ADDR NUM task_block.go:LINE] [ NUM] Interrupt queued", "fatal error: D0302 22:LINE.ADDR NUM task_signals.go:LINE] [ NUM] Notified of signal 7", "fatal error: I0229 00:LINE.ADDR NUM compat.go:LINE] Uncaught signal: \"killed\" (9), PID: 4199, TID: 4207, fault addr: 0", "corrupted report", "fatal error: D0301 17:LINE.ADDR NUM task_block.go:LINE] [ 1] Interrupt queued", "gvisor boot error: fatal error: newosproc", "FATAL ERROR: loading container NAME: open /syzkaller/managers/main/workdir/gvisor_root/ci-gvisor-main-1.state: no such f", "panic: D1231 04:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1231 04:LINE.ADDR 478 x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1230 14:LINE.ADDR 3027 x:LINE] [ 4596] ADDR: ff ff ff ff 00 00 00 00 0b 00 00 00 00 00 00 00", "panic: D1229 18:LINE.ADDR NUM x:LINE] [ 6299] Syscall 202: denied by seccomp", "panic: D1227 12:LINE.ADDR NUM x:LINE] [ 8347] Fs_base = ADDR", "panic: D1226 18:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1225 01:LINE.ADDR NUM x:LINE] [ 6990] Rdx = ADDR", "panic: D1223 18:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1223 08:LINE.ADDR NUM x:LINE] [ 608] Syscall 202: denied by seccomp", "panic: D1223 05:LINE.ADDR NUM x:LINE] [ 2744] Syscall 202: denied by seccomp", "panic: D1221 11:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1220 03:LINE.ADDR NUM x:LINE] [ 8321] ADDR: d0 ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00", "panic: D1220 07:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: D1219 00:LINE.ADDR NUM x:LINE] [ NUM] ADDR: 07 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00", "panic: D0113 18:LINE.ADDR NUM x:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "panic: D0112 11:LINE.ADDR NUM x:LINE] [ 5884] Syscall 202: denied by seccomp", "panic: D0111 06:LINE.ADDR NUM x:LINE] [ NUM] Transitioning from exit state TaskExitInitiated to TaskExitZombie", "panic: D0110 19:LINE.ADDR 7761 x:LINE] recv [channel @ADDR] Rlerror{Error: 2}", "fatal error: faultD0210 21:LINE.ADDR 1 log.go:LINE] [ 715] ADDR: 00 00 00 00 00 00 00 00 a0 09 5d fd a8 7f 00 00", "fatal error: D1229 00:LINE.ADDR NUM x:LINE] [ 3240] ADDR: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00", "fatal error: D0211 10:LINE.ADDR 1 log.go:LINE] [ 42] ADDR: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00", "fatal error: D0210 22:LINE.ADDR NUM log.go:LINE] [ 5081] ADDR: c7 7a 4a 00 00 00 00 00 06 00 00 00 00 00 00 00", "fatal error: 19:LINE executing program 2:", "gvisor test error: FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF (2)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (9)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (8)", "fatal error: D0130 06:LINE.ADDR 8624 log.go:LINE] [ NUM] ADDR: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (7)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (6)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (5)", "syzkaller: make host failed: failed to run [\"make\" \"host\" \"ci\"]: exit status 2 (2)", "fatal error: unknown caller pc", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (4)", "syzkaller: make target failed: failed to run [\"make\" \"target\"]: exit status 2 (3)", "gvisor boot error: FATAL ERROR: running container: starting container: loading sandbox containers: loading container NAME: unexpected end o", "fatal error: D0917 22:LINE.ADDR NUM x:LINE] [ 856] Syscall 202: denied by seccomp", "panic: D1130 20:LINE.ADDR NUM x:LINE] [ 7813] Syscall 202: denied by seccomp", "panic: ptrace status unexpected: got 31, wanted stopped", "gvisor build error (5)", "panic: trying to use inactive address space?", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (3)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1 (2)", "panic: wait failed: the process NUM:LINE exited: 1f (err <nil>)", "panic: D0917 14:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "gvisor build error (4)", "gvisor boot error: FATAL ERROR: error executing /proc/self/exe: no such file or directory", "panic: D0823 17:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "panic: unable to activate mm: creating stub process: resource temporarily unavailable (2)", "panic: unable to activate mm: creating stub process: resource temporarily unavailable", "FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF", "syzkaller: make target failed: failed to run [\"make\" \"target\"]: exit status 2 (2)", "gvisor test error: panic: error initializing first thread: resource temporarily unavailable", "gvisor boot error: FATAL ERROR: Error reading mounts file: error unmarshaling mounts: unexpected end of JSON input", "FATAL ERROR: retrieving stacks: getting sandbox NAME failed: EOF", "FATAL ERROR: retrieving stacks: getting sandbox NAME failed: connection reset by peer", "panic: ptrace status unexpected: got 9, wanted stopped (3)", "fatal error: out of memory", "gvisor test error: fatal error: newosproc", "FATAL ERROR: retrieving stacks: connecting to control server at pid X: connection refused", "gvisor boot error: FATAL ERROR: running container: creating container: creating control server socket for sandbox NAME: address already in", "FATAL ERROR: error waiting on pid X: error waiting on pid X in sandbox NAME failed: EOF", "fatal error: fault", "panic: Signal-induced panic", "fatal error: D0105 22:LINE.ADDR 1 x:LINE] [ 5264] Transitioning from exit state TaskExitInitiated to TaskExitZombi", "panic: node.Readdir returned offset 102 less than input offset NUM", "gvisor boot error (4)", "syzkaller: testing failed: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1", "panic: unable to attach: operation not permitted", "gvisor build error (3)", "gvisor test error: FATAL ERROR: waiting on pid X: waiting on pid X in sandbox NAME failed: EOF", "fatal error: thread exhaustion", "syzkaller: make target failed: failed to run [\"make\" \"target\"]: exit status 2", "panic: D0417 05:LINE.ADDR NUM x:LINE] [ NUM] Syscall 202: denied by seccomp", "fatal error: D0401 05:LINE.ADDR NUM x:LINE] [ 4343] R15 = ADDR", "gvisor build error (2)", "gvisor build error", "syzkaller: testing failed: %v: failed to run [\"go\" \"test\" \"-short\" \"./...\"]: exit status 1", "fatal error: I/O", "Invalid request partialResult in write", "panic: runtime error: slice bounds out of range (2)", "Invalid request partialResult in pwrite64", "DATA RACE in refs.(*WeakRef).init", "fatal error: entry failed", "gvisor boot error: FATAL ERROR: error running container: error creating container: error creating control server socket for sandbox NAME: a", "fatal error: D1222 08:LINE.ADDR NUM x:LINE] [ NUM] Discarding ignored signal 18", "panic: Incrementing non-positive ref count", "fatal error: runtime: split stack overflow", "fatal error: newosproc (2)", "panic: ptrace get fpregs failed: no such process", "panic: error initializing first thread: resource temporarily unavailable (2)", "panic: ptrace get regs failed: no such process (2)", "panic: ptrace set regs (&{R15:LINE R14:LINE R13:LINE R12:LINE Rbp:ADDR Rbx:ADDR R11:LINE R10:ADDR R9:LINE R8:ADDR Rax:LI", "panic: ptrace set fpregs (ADDR) failed: no such process", "panic: ptrace set regs failed: no such process (2)", "gvisor boot error: init process did not start", "gvisor test error: lost connection to test machine", "gvisor boot error (2)", "panic: munmap(ADDR, ADDR)) failed: function not implemented", "panic: IncRef([ADDR, ADDR)): attempted to IncRef on unallocated pages [ADDR, ADDR):", "panic: error mapping run data: error mapping runData: cannot allocate memory", "panic: interface conversion: unix.Receiver is nil, not *unix.queueReceiver", "https://github.com/dvyukov/gvisor.git boot error", "gvisor test error", "panic: ptrace sysemu failed: no such process", "fatal error: runtime: cannot allocate memory", "fatal error: runtime: out of memory", "fatal error: I0629 14:LINE.ADDR NUM x:LINE] [ NUM] Error opening /bin/sh: no such file or directory", "FATAL ERROR: error running container: err waiting on container NAME: EOF", "lost connection to test machine", "panic: executor 2: failed: clock_gettime failed (errno 14)", "fatal error: newosproc", "panic: executor 3: failed: output overflow (errno 110)", "panic: error initializing first thread: resource temporarily unavailable"]}